### ISSUE TITLE
Installation instructions do not mention libprotobuf-mutator

### ISSUE THREAD

**Issue by grrussel** [haoxintu/RemCCG#1]
Hi!

There is a dependency on libprotobuf-mutator to build RemCCG and this is not mentioned in the instructions for setup

Could that be added?

Cheers,
George

**Comment by haoxintu** [comment]
Hi @grrussel,

The `libprotobuf-mutator` was used in the initial version of RemCCG. We have tried to remove it in the current released version to make the implementation succinct.

Btw, did you encounter any building issue revenant to the `libprotobuf-mutator`? Please let me know if so.

Thanks,
Haoxin

**Comment by grrussel** [comment]
There is a link time dependency on it

This is mentioned in the CMakeLists file; I could not link the RemCCG executable until I had installed a version of the mutaotr library

https://github.com/haoxintu/RemCCG/search?q=mutator

**Comment by haoxintu** [comment]
Hi @grrussel,

Thanks for pointing this issue out. I have cleared some irrelevant dependencies here b2cac79 and also tested it. Now, it should be ok without the dependence on `libprotobuf-mutator`.
